{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-collector.config-map") -}}
{{- define "ffc-demo-collector.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  EVENT_HOST: {{ quote .Values.container.eventHost }}
  EVENT_PORT: {{ quote .Values.container.eventPort }}
  EVENT_MECHANISM: {{ quote .Values.container.eventMechanism }}
  EVENT_CLIENT_ID: {{ quote .Values.container.eventClientId }}
  EVENT_CONSUMER_GROUP_ID: {{ quote .Values.container.eventConsumerGroupId }}
  CLAIM_UPDATE_TOPIC_NAME: {{ quote .Values.container.claimUpdateTopicName }}
  CLAIM_UPDATE_TOPIC: {{ quote .Values.container.claimUpdateTopic }}
  CLAIM_UPDATE_FROM_BEGINNING: {{ quote .Values.container.claimUpdateFromBeginning }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  {{- if .Values.pr }}
  EVENT_ROUTING_KEY: {{ .Values.name }}-{{ .Values.pr }}
  {{- end }}
{{- end -}}
