{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-collector.container-secret") -}}
{{- define "ffc-demo-collector.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  {{- end }}
{{- end -}}
